### PR TITLE
Refactoring and admin page redux refactor

### PR DESCRIPTION
**Pull request by maaverik**
Going slow and steady this time :)

### CODE REVIEW

**Comment by mradenovic** [comment]
Hey, no offense, but I thought you abandoned this branch completely 😄. You shouldn't have so many meaningless merge commits on a new pull request. I started working on it too. There is a lot of work. How about I start the new branch and then we can work together?

**Comment by maaverik** [comment]
I just noticed all these merge commits, not sure why these show up :confused:, I'll get rid of those. 

I didn't exactly abandon the old branch, it was a pretty busy week :weary: so I thought I'd continue when I felt less exhausted. 

Sure, working together sounds great. And just in case you're curious, the build failure in my previous PR was due to importing setInfoPopupMessage in asyncActions/DeleteQueue.js

**Comment by mradenovic** [comment]
Check #550. Let's do components one by one. See if you can merge or copy paste work that was not already done, without renaming files. I'm working mostly on `Token.jsx` right now. You can use storybook to work on the component in isolation (let me know if you need help with that). 
 
Keep commits atomic and buildable, even if it breaks the behavior (e.g. component does not update properly).

Make pull requests toward `refactor-admin-page`.

**Comment by maaverik** [comment]
Cool, I'll post updates there.

**Pull request closed without merging**
