### PR TITLE
Ripple Effect for Buttons on Click 

### PR DESCRIPTION
**Pull request by jithinlal**

### CODE REVIEW

**Comment by jithinlal** [comment]
Added a light hue when hovering, and a ripple effect upon click

**Comment by daltonfury42** [comment]
Hi @jithinlal 

The light hue on hovering and the ripple effect is looking nice on the outlined buttons we are having.

In the case of the filled buttons (like the one on homepage), earlier we used to have it turn white+outlined on hover. The current change LGTM. @maaverik How about we merge this, and then we ask @akashkbaburajan and @raima-zachariah for feedback.

**Comment by daltonfury42** [comment]
One more thing, a thin blue outline comes around the last button that was clicked:

image

Can we disable that? (Around the refresh button in this screenshot)

**Comment by maaverik** [comment]
The blue outline is specific to chrome, I've never seen it in firefox. But there must be a way to disable it since I haven't seen this on other sites in chrome. @jithinlal in case you find out how to deal with it, you can add the change later. Other than that, things look good. Great job.

**Review by maaverik — APPROVED** [review]

**Comment by daltonfury42** [comment]
I did some googling, and `button:focus { outline: none; }` should do it

**Comment by daltonfury42** [comment]
According to [this](https://medium.com/hackernoon/removing-that-ugly-focus-ring-and-keeping-it-too-6c8727fefcd2) guy, it might affect people using a non-pointer device. He has a solution for it, but in our case, if we do:

```
button:focus { 
  outline: none; 
  // increase the border thickness a bit
}
```
it might take care of that too... @jithinlal what do you think?

**Comment by jithinlal** [comment]
lemme check on this

**Comment by jithinlal** [comment]
closing this pull request to include the border none for chrome browsers.

**Pull request closed without merging**
