### PR TITLE
Experiment: Slider Tweak

### PR DESCRIPTION
**Pull request by daltonfury42**
@maaverik This slider library that we are using, is a pain to control. The three dots at the bottom was not having proper margin, so I removed it. They also have a autoplay feature, which I enabled, to see what it would be like... What do you think?

If you didn't like autoplay, I can remove that, is it looking like too much motion on the page?

### CODE REVIEW

**Comment by daltonfury42** [comment]
Removing this was my main objective:

image

**Comment by maaverik** [comment]
The autoplay doesn't look bad. But the arrows are lost when I use mobile view on the preview so that's a problem. And the autoplay stopped after I enabled mobile view. It doesn't start even after switched back to desktop view. Is it the same on your side?

**Comment by daltonfury42** [comment]
Let me investigate a bit more...

1) The arrows automatically disappear on small screens to save space, it's a feature not a bug.

2) The autoplay stopping on switching modes, I could not reproduce it here. A normal user won't switch like that, so hope that's ok

3) Marking this as WIP. I want to play a bit more
3a) I don't want two autoplaying sliders next to each other... That combined the loaders doesn't look very good.
3b) I want to somehow control it's width.. limited it to some fixed REM.

**Comment by daltonfury42** [comment]
#210 has some examples of layouts, which might be better than a slider... let's not use sliders.

**Pull request closed without merging**
