### PR TITLE
Trying out react-snap for static html rendering

### PR DESCRIPTION
**Pull request by maaverik**
https://web.dev/prerender-with-react-snap/

I can't test this out perfectly locally. The homepage is loading fine as a static html file, but I can't test the rest of the pages since it's blocked by CORS since I'm using a different localhost port for serving the prod build. If we can test this out with the new preview feature and make sure it works fine, we can merge it.

P.S., the styling on the homepage needs to be fixed ASAP. I'm managing by manually removing the svg and the benefits-info part for testing.

### CODE REVIEW

**Comment by daltonfury42** [comment]
Oh wow. If react-snap works, it will be really nice.

I am thinking of disabling cors entirely. It's just giving is problems and not solving anything.

Let me see if previews work, give me some time.

**Comment by maaverik** [comment]
Let me know once the feature is ready. I have the sentry changes also done. We can use the feature to test that out too.

**Comment by daltonfury42** [comment]
Closing and reopening to test the preview branch

**Comment by daltonfury42** [comment]
@maaverik can you pull new-frontend into this branch and reopen the PR?

**Comment by daltonfury42** [comment]
@maaverik I had to make some amplify side changes to snap to build, (https://github.com/puppeteer/puppeteer/issues/765#issuecomment-445334163) now the preview is coming, but the CORS issue is still there. I'll debug later, but you also take a look.

**Comment by daltonfury42** [comment]
@maaverik We had to remove CORS for preview envs to work. Feel free to approve and merge, then the backend calls would start working. 

https://github.com/SimplQ/simplQ-backend/pull/82

**Comment by maaverik** [comment]
The backend calls work fine after removing the CORS check. From what I've seen so far, directly opening the admin page results in styling problems whereas accessing it through the homepage works fine. I'll have to look into this.

**Comment by daltonfury42** [comment]
Yes, that's happening here for me on your branch too. I'll clean up the homepage bugs soon

**Comment by maaverik** [comment]
I'll fix it here. I prefer not having our working branch filled with bugs.

**Comment by maaverik** [comment]
I haven't figured out why the styles get messed up in the admin page yet. Since I'll be working on redesigning the admin page anyway, I'll do that first to see if it automagically somehow fixes things which is what usually happens in cases like this.

**Comment by maaverik** [comment]
I was never able to figure out the cause for the CSS issues and our site's SEO is good now anyway, so closing this.

**Pull request closed without merging**
