### PR TITLE
Add scroll animations to home page

### PR DESCRIPTION
**Pull request by daltonfury42**
A quick experiment! 

Inspired by https://absurd.design
Powered by https://michalsnik.github.io/aos/

Preview: https://animate.dpmhbfuiok7f8.amplifyapp.com/

### CODE REVIEW

**Comment by maaverik** [comment]
This is a nice addition. I noticed a few parts that are not very smooth though. In the Why SimplQ section, the first two images always fade in together while the third one comes later. Could you make all three fade in together or make them fade in one after the other independently?  The create queue section below it looks great, but the join queue section fades in a little late than I would like. The create queue section fades in when I almost scroll to the middle of the section while the join queue section waits till I reach the bottom of the section to fade in, which I personally don't like. Could you try making it fade in like the create queue section?

**Comment by daltonfury42** [comment]
I had been experimenting with different approaches in the different sections. 

1. Why SimplQ section: Independent for each card. 
2. How it works section: Fade up, all together, overrode a deply `data-aos-duration="800"`
3. How to join: Independent, coming from each direction

For 1, (Why simplQ), agreed, zoom in all at once might would be better. Let me know
For 3 (How to join) I think this is happening because it's three independent things fading in... not all at one go. This might be difficult to get around.

**Comment by daltonfury42** [comment]
I don't want both create queue and  join queue to have the same variation, each adjacent section animations should be different.

**Comment by maaverik** [comment]
The Why simplQ part is much better now. I still have mixed feelings about the join simplQ part taking so long to fade in but it's not a big deal.

**Review by maaverik — APPROVED** [review]

**Pull request merged**
