### PR TITLE
Fix z-indexes for nav and overlay

### PR DESCRIPTION
**Pull request by devashishpuri**

### CODE REVIEW

**Comment by daltonfury42** [comment]
Sorry this is a duplicate of #361

**Comment by maaverik** [comment]
This looks like it works. It's doesn't solve the core problem I guess, but I can't think of any side effects right now. @daltonfury42, can you check if you notice any problems with this change?

**Comment by maaverik** [comment]
Looks like this works now. @daltonfury42 could you also check?

**Comment by daltonfury42** [comment]
Respecting the fact that someone else was already working on this, I had closed this PR as a duplicate. (#361)

**Comment by maaverik** [comment]
#361 solved the core problem while this PR was more of a workaround, so we'll go with that one. Thanks for the effort @devashishpuri.

**Pull request closed without merging**
