### PR TITLE
Add chat popup

### PR DESCRIPTION
**Pull request by daltonfury42**

### CODE REVIEW

**Review by maaverik — APPROVED** [review]

**Comment by maaverik** [comment]
The way it is right now, this shows up on all pages including the status and join pages. We should maybe restrict this to the home and admin pages.

**Comment by maaverik** [comment]
Actually, it's fine. No problems with showing this everywhere.

**Comment by daltonfury42** [comment]
Right, and even more places. I’ll fix this weekend probably

**Comment by daltonfury42** [comment]
I think it should not pop up on mobile, as it takes up the entire space and
is a bit intrusive.

But Pavan and Sajmal says that’s fine. Maybe I feel so because my screen
size is very small.

It’s not at it’s best state currently, I’ll need to iterate more.

**Pull request merged**
