### PR TITLE
Changed directory to run npm install in

### PR DESCRIPTION
**Pull request by maaverik**
Should fix the issue with lint action not working

### CODE REVIEW

**Comment by maaverik** [comment]
Still fails even though npm install ran fine this time

**Comment by daltonfury42** [comment]
This is how you can set the working directory https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

**Comment by daltonfury42** [comment]
I guess it's not because of directory. One thing we can do is to report the issue upstream..

For backend, the way @thehamzarocks has set it up is to automatically lint and fix errors. Is frontend also like that?

**Comment by maaverik** [comment]
Could you merge this with your token service branch? It has outdated changes like apis.js and queue.js

**Pull request merged**
