### PR TITLE
Refactor component names

### PR DESCRIPTION
**Pull request by mradenovic**
- Rename `index.jsx` to `ComponentName.jsx`
- Use `PascalCase` for `ComponentName.module.scss`
- Use `index.jsx` to re-export component

### CODE REVIEW

**Comment by mradenovic** [comment]
Only common components will be changed in this PR. Please comment before I do more work.

**Comment by daltonfury42** [comment]
I did some research, and this makes sense.

https://stackoverflow.com/questions/44092341/how-do-index-js-files-work-in-react-component-directories

**Comment by mradenovic** [comment]
The other option would be to get rid of all `index.jsx` files. Then imports would have to be updated too.

The only bad practice in my opinion is to have components within `index.jsx`. It should be what its name says, an index 😄

**Comment by mradenovic** [comment]
common/Nav doesn't have `index.jsx`. A good example of how it works without it.

I was not sure if I should split `Nav.module.scss` in more files, since every component within the folder uses only its own css.

**Review by daltonfury42 — APPROVED** [review]

**Pull request merged**
