### PR TITLE
Fix lint in QueueStatus/

### PR DESCRIPTION
**Pull request by mradenovic**
Missed lint in master branch causes every pull request to autogenerate fix.

### CODE REVIEW

**Comment by mradenovic** [comment]
For some reason, when I run `npm run lint`, it doesn't fix anything.

**Comment by daltonfury42** [comment]
Ah, this is a pain. https://github.com/wearerequired/lint-action/issues/13 

It's mostly two of us running the show here, would you like to join in? I can give you repo write access and add you in the review process for PRs if you are interested.

Just checked and `npm run lint` is working here for me.

**Comment by mradenovic** [comment]
I poorly described the problem. I'll open a new issue for this.

**Comment by mradenovic** [comment]
> It's mostly two of us running the show here, we would love to have you around. Would you like to join as a maintainer? I can give you repo write access and add you in the review process for PRs if you are interested.

That would be nice, just restrict write access to master branch 🤣

**Comment by daltonfury42** [comment]
I've added you as a collaborator. Welcome!

**Comment by mradenovic** [comment]
Thanks! I'll create branches on this repo from now on.

**Pull request closed without merging**
