### PR TITLE
Avoid Movement of Other Components on Expansion

### PR DESCRIPTION
**Pull request by daltonfury42**
The footer and the main content keeps moving up and down when you expand and collapse:

ezgif com-gif-maker

Avoiding this by fixing the footer down below visible screen, and also not centring the text of empty queue. I tried to avoid the latter, but couldn't make both work.

### CODE REVIEW

**Comment by maaverik** [comment]
I'm pretty sure this problem wasn't there last week. What changes did we make to the admin page this week? One of them might have caused this.

**Comment by maaverik** [comment]
I think there used to be more space between the footer and the sidepanel so the expansion used to fill up that space and not move the entire page.

**Comment by daltonfury42** [comment]
I checked out 4 weeks old code https://github.com/SimplQ/simplQ-frontend/commit/00e750cf0a108054237d7fde8c8108029f20a6af and the problem is there.

**Comment by daltonfury42** [comment]
Actually the diff is mostly whitespace changes because I wrapped a lot of css inside one more nesting... The main change is only https://github.com/SimplQ/simplQ-frontend/pull/418/commits/e296a9956ad5f13c63737bf027ec27f00ba884f7 and https://github.com/SimplQ/simplQ-frontend/pull/418/commits/ec246d9dd9a84ce9c00df12cc59e56675273f033

Hide whitespace when you review the diff:
image

**Review by maaverik — APPROVED** [review]

**Comment by maaverik** [comment]
I thought I'd approved already. This hide whitespaces setting is useful :).

**Pull request merged**
