### PR TITLE
Revert "Changed createJoinForm to use redux actions"

### PR DESCRIPTION
**Pull request by mradenovic**
Reverts SimplQ/simplQ-frontend#553

This should be merged with `refactor-admin`page, not `master`.

### CODE REVIEW

**Comment by mradenovic** [comment]
@maverik, was `create-join-form` based on master?

**Comment by maaverik** [comment]
Yes, it was branched off from master and is independent of the admin page changes. You don't need to revert.

**Comment by mradenovic** [comment]
OK, I'm sorry, I panicked 😊 I merged it, and tested it, and discovered a bug and I thought it was this PR 🤣

**Comment by daltonfury42** [comment]
@mradenovic No need to panic 😛 

When we merge to master, our dev site at dev.simplq.me only gets updated, so it's fine. ✌️

**Pull request closed without merging**
